name: test
version: 0.1.0
author: Dart Team
dependencies:
  appengine:
    path: ../appengine
  cloud_datastore:
    path: ../cloud_datastore
  http_server: any
  memcache:
    path: ../memcache
  mustache: any
  route:
    path: ../route
